### ISSUE TITLE
Run Cargo Clippy

### ISSUE THREAD

**Issue by hardliner66** [stormyzio/timeshot#2]
I just wanted to let you know, there is command called cargo clippy, which is intended to lint rust code and help write better code. You can invoke it with `cargo clippy --all` and what I like to do before making a new release is running `cargo clippy --all -- -D clippy::pedantic` to see even more lints.

**Comment by stormyzio** [comment]
Hello!
Thank you for your comment. I saw a little bit about clippy before but I didn't know exactly what it was and I didn't know it was as simple as that.
Thank you!
